version: "3.8"

services:
  db:
    container_name: todolist-database
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todolist_pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 3s
      timeout: 3s
      retries: 3

  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./todolist/:/opt/todolist
      - ./core/:/opt/core
      - ./goals/:/opt/goals
  collect_static:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    command: python3 manage.py collectstatic -c --no-input
    volumes:
      - django_static:/opt/static

  front:
    image: sermalenk/skypro-front:lesson-37
    restart: always
    ports:
      - "80:80"
    depends_on:
      collect_static:
          condition: service_completed_successfully
    volumes:
      - django_static:/usr/share/nginx/html/static/
      - ./deploy/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  todolist_pg_data:
    driver: local
  django_static:
    driver: local
