# Generated by Django 4.1.4 on 2023-01-16 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goalcategory',
            old_name='name',
            new_name='title',
        ),
    ]
