# Generated by Django 4.1.4 on 2023-01-16 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_goal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='deadline',
            new_name='due_date',
        ),
    ]
