version: "3.8"

services:
  db:
    container_name: todolist-database
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - todolist_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${DB_USER} -d ${DB_NAME}
      interval: 15s
      timeout: 15s
      retries: 5

  api:
    image: alstacon/todolist:${TAG_NAME}
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy

  bot:
    image: alstacon/todolist:${TAG_NAME}
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
      api:
        condition: service_started
    command: python3 manage.py runbot

  collect_static:
    image: alstacon/todolist:${TAG_NAME}
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_healthy
    command: python3 manage.py collectstatic -c --no-input
    volumes:
      - django_static:/opt/static/

  front:
    image: sermalenk/skypro-front:lesson-38
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      collect_static:
        condition: service_completed_successfully
      api:
        condition: service_started
    volumes:
      - django_static:/opt/static/
      - /etc/letsencrypt/:/etc/letsencrypt/
      - /etc/nginx/conf.d/todocon.ga.conf:/etc/nginx/conf.d/default.conf


volumes:
  todolist_pg_data:
    driver: local
  django_static:
    driver: local
